# Generated by Django 3.1.5 on 2022-01-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20220126_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='age',
            new_name='user_age',
        ),
    ]
