# Generated by Django 3.1.5 on 2022-01-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20220126_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='contact_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_age',
            field=models.IntegerField(null=True),
        ),
    ]
